
spring:
  datasource:
    url: jdbc:mysql://192.168.0.111:3306/db01?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

elasticjob:
  reg-center:
    server-lists: 192.168.200.131:2181
    namespace: my-job-namespace
  jobs:
    dataSyncJob:
      elasticJobClass: org.example.job.DataSyncJob
      cron: "0/20 * * * * ?"   # 每10秒执行一次（测试用）
      sharding-total-count: 5  # 分成5片
      sharding-item-parameters: "0=shard_0,1=shard_1,2=shard_2,3=shard_3,4=shard_4"
server:
  port: 8091