server:
  port: 51601

spring:
  application:
    name: gateway-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_claim_rewards?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: 192.168.200.131:8848
      config:
        server-addr: 192.168.200.131:8848
        import-check:
          enabled: false

    gateway:
      routes:
        - id: award-service
          uri: lb://award-service
          predicates:
            - Path=/api/rewards/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
            - Method=POST, GET

    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

logging:
  level:
    org.springframework.cloud.gateway: debug
