dubbo:
  application:
    name: demo-provider
    service-config-mapping: true
    service-discovery:
      migration: FORCE_INTERFACE
  protocol:
    name: dubbo
    port: 20880  #   -Ddubbo.protocol.port=20882
  registry:
    address: zookeeper://192.168.200.131:2181
  config-center: # 显式声明配置中心（可选，若 registry 和 config-center 相同可省略）
    address: zookeeper://192.168.200.131:2181
  metadata-report:
    address: zookeeper://192.168.200.131:2181
  provider:
    weight: 100  # 初始权重（可通过配置或动态修改）
