dubbo:
  application:
    name: demo-provider
    service-config-mapping: true
    service-discovery:
      migration: FORCE_INTERFACE
  protocols:
    dubbo:
      name: dubbo
      port: 20880
  protocol:
    name: dubbo
    port: 20880  #   -Ddubbo.protocol.port=20882
  registry:
    address: zookeeper://192.168.200.131:2181
  config-center: # 显式声明配置中心（可选，若 registry 和 config-center 相同可省略）
    address: zookeeper://192.168.200.131:2181
  metadata-report:
    address: zookeeper://192.168.200.131:2181
  provider:
    weight: 100  # 初始权重（可通过配置或动态修改）

server:
  port: 8089


spring:
  application:
    name: dubbo-provider-inventory-service
  jmx:
    enabled: false  # 完全禁用 JMX
    application:
      admin:
        enabled: false # 禁用 Spring Boot Admin 自动注册


  # 库存数据库配置
  datasource:
    url: jdbc:mysql://192.168.50.116:3307/inventory_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: module2consumer.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl